### ISSUE TITLE
R_USER not defined

### ISSUE THREAD

**Issue by CPernet** [lecy/RMD-to-Jupyter#3]
Hi there,

I installed everything as indicated, and set up an environment/path to R, yet when running the script I receive a R_USER not defined - any chance of having a ready made fix for this? (Win 7, python 3.7, R3.6)

thx
cyril

**Comment by lecy** [comment]
Hi Cyril - 

This script is a little out-dated, partly because much of the functionality of Jupyter has been incorporated into RMD documents, and partly because R Studio can now work with Notebooks. 

I haven't run the script in awhile, would have to look over it, but perhaps there is a current option for what you are trying to do. What specifically are you trying to accomplish? 

Jesse

**Comment by CPernet** [comment]
I've got a friend who made Rmd notebooks (e.g. https://github.com/GRousselet/bootstrap/blob/master/pb.Rmd) that I wanted to load/run in jupyter (I think for demos it's much nicer) -- looks like your code is running (creating 0kb file) up to that user issue (I even changed the path to the generic environment rather than user environment JIC but no luck) - thx for looking into it
